"""add_payment_transaction_table

Revision ID: 622a4c7fdc7b
Revises: d46d46bb582d
Create Date: 2026-08-20 08:59:42.068762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '622a4c7fdc7b'
down_revision = 'd46d46bb582d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transaction_course_id'), 'payment_transaction', ['course_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_created_at'), 'payment_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transaction_student_id'), 'payment_transaction', ['student_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_transaction_id'), 'payment_transaction', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transaction_transaction_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_student_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_created_at'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_course_id'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    # ### end Alembic commands ###
