"""add_rag_and_ai_tutor_tables

Revision ID: 72663c1b3001
Revises: 70995c78aaf7
Create Date: 2026-08-14 09:27:20.086431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72663c1b3001'
down_revision = '70995c78aaf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tutor_conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tutor_conversation_course_id'), 'ai_tutor_conversation', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_tutor_conversation_lesson_id'), 'ai_tutor_conversation', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_ai_tutor_conversation_student_id'), 'ai_tutor_conversation', ['student_id'], unique=False)

    op.create_table('lesson_chunk_embedding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('content_chunk', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('start_timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('end_timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_chunk_embedding_course_id'), 'lesson_chunk_embedding', ['course_id'], unique=False)
    op.create_index(op.f('ix_lesson_chunk_embedding_lesson_id'), 'lesson_chunk_embedding', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_chunk_embedding_section_id'), 'lesson_chunk_embedding', ['section_id'], unique=False)

    op.create_table('ai_tutor_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('was_escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_tutor_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tutor_message_conversation_id'), 'ai_tutor_message', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tutor_message_conversation_id'), table_name='ai_tutor_message')
    op.drop_table('ai_tutor_message')
    op.drop_index(op.f('ix_lesson_chunk_embedding_section_id'), table_name='lesson_chunk_embedding')
    op.drop_index(op.f('ix_lesson_chunk_embedding_lesson_id'), table_name='lesson_chunk_embedding')
    op.drop_index(op.f('ix_lesson_chunk_embedding_course_id'), table_name='lesson_chunk_embedding')
    op.drop_table('lesson_chunk_embedding')
    op.drop_index(op.f('ix_ai_tutor_conversation_student_id'), table_name='ai_tutor_conversation')
    op.drop_index(op.f('ix_ai_tutor_conversation_lesson_id'), table_name='ai_tutor_conversation')
    op.drop_index(op.f('ix_ai_tutor_conversation_course_id'), table_name='ai_tutor_conversation')
    op.drop_table('ai_tutor_conversation')
    # ### end Alembic commands ###
